# Site settings
title: Looping's Pictures
email: tiffany.vachez@outlook.com
description: ""
baseurl: ""
# url: "https://tiffany.vachez.com"
github_username: bloodstorms
# logo: /img/tiffanyvachez_logo.png

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-autoprefixer
